sudo: false
language: node_js
node_js:
  - "iojs-v3"
  - "iojs-v2"
  - "iojs-v1"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - "npm install -g npm@2.1.18"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@2.11.x && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.8"
notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
